kind: pipeline
type: kubernetes
name: default

steps:
- name: upload_image_dev
  image: docker/compose:1.24.1
  commands:
    - echo Ola!
    - echo 2
    - echo 3
    - sleep 60
    - echo 4
    - echo 5
    - echo 6
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request